site_name: CoopyrightCode
site_url: https://licence.coopyrightcode.com
site_author: Ludovic FERNANDEZ, Alien6
site_description: >-
  CoopyrightCode Licence Light

# Repository
repo_name: coopyrightcode/licence-light
repo_url: https://github.com/coopyrightcode/licence-light

# Copyright
copyright: Copyright &copy; 2024 Alien6

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  theme:
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate

extra:
  generator: false
  social:
  - icon: /fontawesome/regular/envelope
    name: send us an email
    link: mailto:contact@alien6.com
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_javascript:
  - assets/javascripts/feedback.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Overview: overview.md
  - The Project:
    - Vision & Mission: project/mission.md
    - Roadmap: project/roadmap.md
  - Light Version:
    - Licence: light/licence.md
    - Usage: light/usage.md
    - FAQ: light/faq.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
